services:
  db:
    image: postgres:16.1-bullseye
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
